
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frndprofile.java
 *
 * Created on Mar 24, 2012, 11:52:38 PM
 */
/**
 *
 * @author DIVYAM
 */
public class frndprofile extends javax.swing.JFrame {
static String userdata;
    /** Creates new form frndprofile */
    public frndprofile(String s) {
        super(); 
        userdata=s;
        this.setTitle(userdata+"'s PROFILE"); 
           initComponents();
           initComponents1();
        
 		this.setVisible(true); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(192, 213, 241));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1034, 900));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Friendshub.jpg"))); // NOI18N

        jButton11.setText("Search");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton14.setText("Scrapbook");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 246, 235));

        jLabel5.setText("About Me");

        jLabel7.setText("Relationship Status");

        jLabel6.setText("My Passion");

        jLabel8.setText("Political View");

        jLabel9.setText("Living With");

        jLabel10.setText("Hobbies");

        jLabel11.setText("Name");

        jLabel12.setText("Gender");

        jLabel13.setText("Birthday");

        jLabel14.setText("City");

        jLabel15.setText("Religion");

        jLabel16.setText("Country");

        jLabel17.setText("Languages");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel16)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29))))
        );

        jButton15.setText("Add as Friend");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton6.setText("Friend List");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Edit profile");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("home");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setText("Friend list");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Scrapbook");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton8)
                                .addGap(58, 58, 58)
                                .addComponent(jButton14))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButton7)
                                .addGap(88, 88, 88)
                                .addComponent(jButton6)
                                .addGap(87, 87, 87)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(292, 292, 292)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jButton3))))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addGap(4, 4, 4))
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton14)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton2)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void initComponents1()
{
    jButton1.setText(userdata+"'s Frndlist");
    client c3=new client("addas"+userdata);
    if(c3.strrecv==null)
    {
         jButton15.setText("Add as Friend");
         jButton15.setVisible(true);
         jButton4.setVisible(false);
    }
    else if(c3.strrecv.indexOf(welcome.currentuser)!=-1)
    {
        
 	     
 	    jButton4.setText(userdata+"'s Scrapbook");
            jButton4.setVisible(true);
            jButton15.setVisible(false);
    }
    else
    {    jButton15.setText("Add as Friend");
    jButton15.setVisible(true);
         jButton4.setVisible(false);
}
        client cfr=new client("noscr"+userdata);
    client pic = new client("photo"+userdata);
    jLabel4.setIcon(new ImageIcon("c:/socialnet_java/photos/"+userdata+".jpg"));
    
    client c=new client();
  String temp,fullnm,fnm,lnm;
  for(int i=0;i<13;i++)
  { 
      switch(i)
      {    
          case 0:
              fnm=c.client("select fname from logins where username='"+userdata+"';",0);    
              lnm=c.client("select lname from logins where username='"+userdata+"';",0);
              fullnm=fnm+" "+lnm;
              jLabel18.setText(fullnm);
              break; 
              
          case 1:
              temp=c.client("select gender from logins where username='"+userdata+"';",0);
              jLabel19.setText(temp);
              break; 	                
 		             
          case 2:
              jLabel20.setText(c.client("select bday from logins where username='"+userdata+"';",0));               
              break; 	
          
          case 3:
              jLabel21.setText(c.client("select city from logins where username='"+userdata+"';",0));     
              break; 	
          
          case 4:
              jLabel22.setText(c.client("select religion from logins where username='"+userdata+"';",0));    
              break; 	
          case 5:
              jLabel23.setText(c.client("select country from logins where username='"+userdata+"';",0));     
              break; 	
          case 6:
              jLabel25.setText(c.client("select relstatus from logins where username='"+userdata+"';",0));               
              break; 	
          case 7:
              jLabel26.setText(c.client("select passion from logins where username='"+userdata+"';",0)); 
              break; 
          case 8:
              jLabel27.setText(c.client("select polview from logins where username='"+userdata+"';",0)); 
              break; 
          case 9:
              jLabel28.setText(c.client("select living from logins where username='"+userdata+"';",0)); 
              break;
          case 10:
              jLabel29.setText(c.client("select hobbies from logins where username='"+userdata+"';",0)); 
              break;
          case 11:
              jLabel24.setText(c.client("select abtme from logins where username='"+userdata+"';",0)); 
              break;
          case 12:
              jLabel30.setText(c.client("select lang from logins where username='"+userdata+"';",0)); 
              break;
              
      }
  }
 

  
}

 
private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
this.setVisible(false);
searchres sres=new searchres();
sres.setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton11ActionPerformed

private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
   client client = new client("scrap"+welcome.currentuser);
              
              try{
 		
 		FileReader fr = new FileReader("c:/socialnet_java/temp.txt");
        BufferedReader br = new BufferedReader(fr);
        
       
        String firstline=br.readLine();
        firstline=firstline.trim();
      
        
        int c=Integer.parseInt(firstline);
         
        int j;
        
        int maxfrm;
       if(c==0) maxfrm=1;
       else if((c%3)==0) 
            maxfrm=c/3;
       else  maxfrm=(c/3)+1;
      
        scrapbook array[] =new scrapbook [maxfrm];
       
        String temp;
        
        String src[]=new String [3];
        for(int i=0;i<maxfrm;i++)
           { 
               src[0]=src[1]=src[2]="";
             for(j=0;j<3;j++)
             { 
             
             if(br.read()==-1)
           	 break;  
             temp=br.readLine();             
             
           	          
           	 while(!(temp.equals("~!@#$%")))
           	 {
           	 	src[j]+=temp+"\n";
           	 	temp=br.readLine();
           	 }     
                       	    	 
             }
             	
               if( c%3==1 && i==maxfrm-1) src[2]="";
               array[i]=new scrapbook(src[0],src[1],src[2],array,i,c,welcome.currentuser); 
           }
          
             br.close();
             fr.close();
             this.setVisible(false);
           }
           catch(Exception e1) 
                { 
                }
    
    // TODO add your handling code here:
}//GEN-LAST:event_jButton14ActionPerformed

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

            int confirm = JOptionPane.showConfirmDialog(rootPane, "Do you really wanna send friend request..??");
      System.out.println(""+confirm);
            if(confirm==0)
       {        
                      client client = new client("#####"+welcome.currentuser+"*"+userdata);
        frndprofile others = new frndprofile(userdata);
 			this.setVisible(false);
                 jLabel1.setText("Request pending");
                       jButton15.setVisible(false);          
       }
        
     
    // TODO add your handling code here:
}//GEN-LAST:event_jButton15ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 this.setVisible(false);
profile pq=new profile(welcome.currentuser);
pq.setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton8ActionPerformed

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
client c=new client("frien"+welcome.currentuser);
 		
 		             int start=0;
                     int friends=0;
                     int temp1;
                     if(c.strrecv!=null)
                     {int last=c.strrecv.length();
                     int max1;
                     String arr[]=new String[6];
                     
                     
                     while(start<last)
                        { if((temp1=c.strrecv.indexOf("$",start))!=-1)
                          {
                          	friends++;
                          	start=temp1+1;
                          }
                          start++;
                          
                        }
                     
                     
                 if(friends==0)
                     max1=0;
                     else 
                     if(friends%6==0)
                     max1=friends/6;
                     else
                     max1= friends/6+1;
                                     
                     friendlist[] fri =new friendlist[max1];
                     
                        int frameno=0;
                        int count=0;
                        int cc;
                        int c1;
                        int photo=1;
                        start=0;
                        String temp=null;
                        while(start<last)
                             {  
                                if(count==6)
                                  {for(int i=0;i<6;i++) 
                                   if(arr[i]!=null)
                                   {
                       
                        client client = new client("photo"+arr[i]);
                                   	photo++;
                                   }
                                   
                                   fri[frameno]=new friendlist(arr,welcome.currentuser,fri,max1-1,frameno++);
                                  	for(int i=0;i<6;i++)
                                      arr[i]=null; 
                                     count =0; 
                                  }
                                
                             	if((cc=c.strrecv.indexOf("$",start))!=-1)
                             	   { temp=c.strrecv.substring(start,cc);
                             	     start=cc+1;
                             	     
                             	     if((c1=temp.lastIndexOf("#"))!=-1)
                             	     temp=temp.substring(c1+1,temp.length());
                             	     if((c1=temp.lastIndexOf("*"))!=-1)
                             	     temp=temp.substring(c1+1,temp.length());
                             	      arr[count++]  =temp;
                             	      
                             	   }
                             	   else start++;
                             	   
                             	
                             	
                             	
                             }
                             
                             if(frameno==max1-1) 
                               {  
                                   for(int i=0;i<count;i++) 
                                   if(arr[i]!=null)
                                   { 
                    client client = new client("photo"+arr[i]);
                                   	
                                   	photo++;
                                   	}
                                   
                                   fri[frameno]=new friendlist(arr,welcome.currentuser,fri ,max1-1,frameno++);
                               
                                    
                                     
                                }             
                           }       
 		  	this.setVisible(false);
        // TODO add your handling code here:
        }//GEN-LAST:event_jButton6ActionPerformed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.setVisible(false);
editprof wl1=new editprof(welcome.currentuser);
wl1.setVisible(true);
            // TODO add your handling code here:
        }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
info i=new info(welcome.currentuser);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
client c=new client("frien"+userdata);
 		
 		             int start=0;
                     int friends=0;
                     int temp1;
                     if(c.strrecv!=null)
                     {int last=c.strrecv.length();
                     int max1;
                     String arr[]=new String[6];
                     
                     
                     while(start<last)
                        { if((temp1=c.strrecv.indexOf("$",start))!=-1)
                          {
                          	friends++;
                          	start=temp1+1;
                          }
                          start++;
                          
                        }
                     
                   
                 if(friends==0)
                     max1=0;
                     else 
                     if(friends%6==0)
                     max1=friends/6;
                     else
                     max1= friends/6+1;
                                     
                     friendlist[] fri =new friendlist[max1];
                    
                        int frameno=0;
                        int count=0;
                        int cc;
                        int c1;
                        int photo=1;
                        start=0;
                        String temp=null;
                        while(start<last)
                             {  
                                if(count==6)
                                  {for(int i=0;i<6;i++) 
                                   if(arr[i]!=null)
                                   {
                        
                        client client = new client("photo"+arr[i]);
                                   	photo++;
                                   }
                                  
                                   fri[frameno]=new friendlist(arr,userdata,fri,max1-1,frameno++);
                                  	for(int i=0;i<6;i++)
                                      arr[i]=null; 
                                     count =0; 
                                  }
                                
                             	if((cc=c.strrecv.indexOf("$",start))!=-1)
                             	   { temp=c.strrecv.substring(start,cc);
                             	     start=cc+1;
                             	     
                             	     if((c1=temp.lastIndexOf("#"))!=-1)
                             	     temp=temp.substring(c1+1,temp.length());
                             	     if((c1=temp.lastIndexOf("*"))!=-1)
                             	     temp=temp.substring(c1+1,temp.length());
                             	      arr[count++]  =temp;
                             	      
                             	   }
                             	   else start++;
                             	   
                             	
                             	
                             	
                             }
                             
                             if(frameno==max1-1) 
                               {  
                                   for(int i=0;i<count;i++) 
                                   if(arr[i]!=null)
                                   { 
                    client client = new client("photo"+arr[i]);
                                   	
                                   	photo++;
                                   	}
                                   
                                   fri[frameno]=new friendlist(arr,userdata,fri ,max1-1,frameno++);
                                
                                     
                                }             
                           }       
 		  	this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
welcome wl=new welcome();
wl.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
client client = new client("scrap"+userdata);
              
              try{
 		
 		FileReader fr = new FileReader("c:/socialnet_java/temp.txt");
        BufferedReader br = new BufferedReader(fr);
        
       
        String firstline=br.readLine();
        firstline=firstline.trim();
       
        
        int c=Integer.parseInt(firstline);
         
        int j;
        
        int maxfrm;
       if(c==0) maxfrm=1;
       else if((c%3)==0) 
            maxfrm=c/3;
       else  maxfrm=(c/3)+1;
    
        scrapbook array[] =new scrapbook [maxfrm];
      
        String temp;
        
        String src[]=new String [3];
        for(int i=0;i<maxfrm;i++)
           { 
               src[0]=src[1]=src[2]="";
             for(j=0;j<3;j++)
             { 
             
             if(br.read()==-1)
           	 break;  
             temp=br.readLine();             
             
           	      
           	 while(!(temp.equals("~!@#$%")))
           	 {
           	 	src[j]+=temp+"\n";
           	 	temp=br.readLine();
           	 }     
                       	    	 
             }
             	
               if( c%3==1 && i==maxfrm-1) src[2]="";
               array[i]=new scrapbook(src[0],src[1],src[2],array,i,c,userdata); 
           }
          
             br.close();
             fr.close();
             this.setVisible(false);
           }
           catch(Exception e1) 
                { 
                }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
   
        
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frndprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frndprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frndprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frndprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new frndprofile(userdata).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
